# Generated by Django 4.2.1 on 2024-08-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_alter_condition_symptoms'),
        ('symptom_checker', '000X_auto'),
    ]

    operations = [
    ]
