# Generated by Django 4.2.1 on 2024-08-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0003_merge_0002_alter_condition_symptoms_000X_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of treatment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='prescription',
            field=models.TextField(blank=True, help_text='Recommended prescription or treatment', null=True),
        ),
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='symptom_checker.condition')),
            ],
        ),
    ]
